### ISSUE TITLE
Добавить FactoryBot и FFaker для генерации рандомных данных

### ISSUE THREAD

**Issue by gruz0** [burn-my-fat/web#5]

**Comment by davydovanton** [comment]
можешь попробовать https://github.com/jodosha/hanami-fabrication вместо фактори бота :)

**Comment by gruz0** [comment]
@davydovanton, благодарю!

**Comment by gruz0** [comment]
@KeyJoo, привет! На самом деле разницы особой нет. Если смотреть на текущие тесты, то пока фейкеры особо и не нужны, как мне кажется.

Ради интереса можно было бы попробовать гем, который @davydovanton порекомендовал.

**Comment by Neyaz** [comment]
@gruz0 Добавил Fabrication и FFaker #57

**Comment by gruz0** [comment]
Благодарю! 👍
